<?php
/**
 * Generated by Haxe 4.0.5
 */

use \php\Boot;
use \php\_Boot\HxClosure;
use \php\_Boot\HxException;
use \_Array\ArrayIterator;

/**
 * An Array is a storage for values. You can access it using indexes or
 * with its API.
 * @see https://haxe.org/manual/std-Array.html
 * @see https://haxe.org/manual/lf-array-comprehension.html
 */
final class Array_hx implements \ArrayAccess {
	/**
	 * @var mixed
	 */
	public $arr;
	/**
	 * @var int
	 * The length of `this` Array.
	 */
	public $length;

	/**
	 * @param mixed $arr
	 * 
	 * @return Array_hx
	 */
	public static function wrap ($arr) {
		#D:\haxe\haxe\std/php/_std/Array.hx:232: characters 3-23
		$a = new Array_hx();
		#D:\haxe\haxe\std/php/_std/Array.hx:233: characters 3-14
		$a->arr = $arr;
		#D:\haxe\haxe\std/php/_std/Array.hx:234: characters 3-31
		$a->length = count($arr);
		#D:\haxe\haxe\std/php/_std/Array.hx:235: characters 3-11
		return $a;
	}

	/**
	 * Creates a new Array.
	 * 
	 * @return void
	 */
	public function __construct () {
		#D:\haxe\haxe\std/php/_std/Array.hx:34: characters 9-36
		$this1 = [];
		#D:\haxe\haxe\std/php/_std/Array.hx:34: characters 3-36
		$this->arr = $this1;
		#D:\haxe\haxe\std/php/_std/Array.hx:35: characters 3-13
		$this->length = 0;
	}

	/**
	 * Returns a new Array by appending the elements of `a` to the elements of
	 * `this` Array.
	 * This operation does not modify `this` Array.
	 * If `a` is the empty Array `[]`, a copy of `this` Array is returned.
	 * The length of the returned Array is equal to the sum of `this.length`
	 * and `a.length`.
	 * If `a` is `null`, the result is unspecified.
	 * 
	 * @param Array_hx $a
	 * 
	 * @return Array_hx
	 */
	public function concat ($a) {
		#D:\haxe\haxe\std/php/_std/Array.hx:39: characters 3-46
		return Array_hx::wrap(array_merge($this->arr, $a->arr));
	}

	/**
	 * Returns a shallow copy of `this` Array.
	 * The elements are not copied and retain their identity, so
	 * `a[i] == a.copy()[i]` is true for any valid `i`. However,
	 * `a == a.copy()` is always false.
	 * 
	 * @return Array_hx
	 */
	public function copy () {
		#D:\haxe\haxe\std/php/_std/Array.hx:43: characters 3-28
		return (clone $this);
	}

	/**
	 * Returns an Array containing those elements of `this` for which `f`
	 * returned true.
	 * The individual elements are not duplicated and retain their identity.
	 * If `f` is null, the result is unspecified.
	 * 
	 * @param \Closure $f
	 * 
	 * @return Array_hx
	 */
	public function filter ($f) {
		#D:\haxe\haxe\std/php/_std/Array.hx:47: characters 3-35
		$result = [];
		#D:\haxe\haxe\std/php/_std/Array.hx:48: characters 15-18
		$data = $this->arr;
		$_g_current = 0;
		$_g_length = count($data);
		$_g_data = $data;
		#D:\haxe\haxe\std/php/_std/Array.hx:48: lines 48-52
		while ($_g_current < $_g_length) {
			$item = $_g_data[$_g_current++];
			#D:\haxe\haxe\std/php/_std/Array.hx:49: lines 49-51
			if ($f($item)) {
				#D:\haxe\haxe\std/php/_std/Array.hx:50: characters 5-22
				$result[] = $item;
			}
		}

		#D:\haxe\haxe\std/php/_std/Array.hx:53: characters 3-22
		return Array_hx::wrap($result);
	}

	/**
	 * Returns position of the first occurrence of `x` in `this` Array, searching front to back.
	 * If `x` is found by checking standard equality, the function returns its index.
	 * If `x` is not found, the function returns -1.
	 * If `fromIndex` is specified, it will be used as the starting index to search from,
	 * otherwise search starts with zero index. If it is negative, it will be taken as the
	 * offset from the end of `this` Array to compute the starting index. If given or computed
	 * starting index is less than 0, the whole array will be searched, if it is greater than
	 * or equal to the length of `this` Array, the function returns -1.
	 * 
	 * @param mixed $x
	 * @param int $fromIndex
	 * 
	 * @return int
	 */
	public function indexOf ($x, $fromIndex = null) {
		#D:\haxe\haxe\std/php/_std/Array.hx:57: characters 7-69
		$tmp = null;
		if (($fromIndex === null) && !($x instanceof HxClosure)) {
			#D:\haxe\haxe\std/php/_std/Array.hx:57: characters 53-69
			$value = $x;
			#D:\haxe\haxe\std/php/_std/Array.hx:57: characters 7-69
			$tmp = !(is_int($value) || is_float($value));
		} else {
			$tmp = false;
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:57: lines 57-64
		if ($tmp) {
			#D:\haxe\haxe\std/php/_std/Array.hx:58: characters 4-50
			$index = array_search($x, $this->arr, true);
			#D:\haxe\haxe\std/php/_std/Array.hx:59: lines 59-63
			if ($index === false) {
				#D:\haxe\haxe\std/php/_std/Array.hx:60: characters 5-14
				return -1;
			} else {
				#D:\haxe\haxe\std/php/_std/Array.hx:62: characters 5-17
				return $index;
			}
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:65: lines 65-72
		if ($fromIndex === null) {
			#D:\haxe\haxe\std/php/_std/Array.hx:66: characters 4-17
			$fromIndex = 0;
		} else {
			#D:\haxe\haxe\std/php/_std/Array.hx:68: lines 68-69
			if ($fromIndex < 0) {
				#D:\haxe\haxe\std/php/_std/Array.hx:69: characters 5-24
				$fromIndex += $this->length;
			}
			#D:\haxe\haxe\std/php/_std/Array.hx:70: lines 70-71
			if ($fromIndex < 0) {
				#D:\haxe\haxe\std/php/_std/Array.hx:71: characters 5-18
				$fromIndex = 0;
			}
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:73: lines 73-77
		while ($fromIndex < $this->length) {
			#D:\haxe\haxe\std/php/_std/Array.hx:74: lines 74-75
			if (Boot::equal($this->arr[$fromIndex], $x)) {
				#D:\haxe\haxe\std/php/_std/Array.hx:75: characters 5-21
				return $fromIndex;
			}
			#D:\haxe\haxe\std/php/_std/Array.hx:76: characters 4-15
			++$fromIndex;
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:78: characters 3-12
		return -1;
	}

	/**
	 * Inserts the element `x` at the position `pos`.
	 * This operation modifies `this` Array in place.
	 * The offset is calculated like so:
	 * - If `pos` exceeds `this.length`, the offset is `this.length`.
	 * - If `pos` is negative, the offset is calculated from the end of `this`
	 * Array, i.e. `this.length + pos`. If this yields a negative value, the
	 * offset is 0.
	 * - Otherwise, the offset is `pos`.
	 * If the resulting offset does not exceed `this.length`, all elements from
	 * and including that offset to the end of `this` Array are moved one index
	 * ahead.
	 * 
	 * @param int $pos
	 * @param mixed $x
	 * 
	 * @return void
	 */
	public function insert ($pos, $x) {
		#D:\haxe\haxe\std/php/_std/Array.hx:82: characters 3-11
		$this->length++;
		#D:\haxe\haxe\std/php/_std/Array.hx:83: characters 3-56
		array_splice($this->arr, $pos, 0, [$x]);
	}

	/**
	 * Returns an iterator of the Array values.
	 * 
	 * @return object
	 */
	public function iterator () {
		#D:\haxe\haxe\std/php/_std/Array.hx:88: characters 3-33
		return new ArrayIterator($this);
	}

	/**
	 * Returns a string representation of `this` Array, with `sep` separating
	 * each element.
	 * The result of this operation is equal to `Std.string(this[0]) + sep +
	 * Std.string(this[1]) + sep + ... + sep + Std.string(this[this.length-1])`
	 * If `this` is the empty Array `[]`, the result is the empty String `""`.
	 * If `this` has exactly one element, the result is equal to a call to
	 * `Std.string(this[0])`.
	 * If `sep` is null, the result is unspecified.
	 * 
	 * @param string $sep
	 * 
	 * @return string
	 */
	public function join ($sep) {
		#D:\haxe\haxe\std/php/_std/Array.hx:92: characters 3-98
		return implode($sep, array_map((Boot::class??'null') . "::stringify", $this->arr));
	}

	/**
	 * Returns position of the last occurrence of `x` in `this` Array, searching back to front.
	 * If `x` is found by checking standard equality, the function returns its index.
	 * If `x` is not found, the function returns -1.
	 * If `fromIndex` is specified, it will be used as the starting index to search from,
	 * otherwise search starts with the last element index. If it is negative, it will be
	 * taken as the offset from the end of `this` Array to compute the starting index. If
	 * given or computed starting index is greater than or equal to the length of `this` Array,
	 * the whole array will be searched, if it is less than 0, the function returns -1.
	 * 
	 * @param mixed $x
	 * @param int $fromIndex
	 * 
	 * @return int
	 */
	public function lastIndexOf ($x, $fromIndex = null) {
		#D:\haxe\haxe\std/php/_std/Array.hx:96: lines 96-97
		if (($fromIndex === null) || ($fromIndex >= $this->length)) {
			#D:\haxe\haxe\std/php/_std/Array.hx:97: characters 4-26
			$fromIndex = $this->length - 1;
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:98: lines 98-99
		if ($fromIndex < 0) {
			#D:\haxe\haxe\std/php/_std/Array.hx:99: characters 4-23
			$fromIndex += $this->length;
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:100: lines 100-104
		while ($fromIndex >= 0) {
			#D:\haxe\haxe\std/php/_std/Array.hx:101: lines 101-102
			if (Boot::equal($this->arr[$fromIndex], $x)) {
				#D:\haxe\haxe\std/php/_std/Array.hx:102: characters 5-21
				return $fromIndex;
			}
			#D:\haxe\haxe\std/php/_std/Array.hx:103: characters 4-15
			--$fromIndex;
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:105: characters 3-12
		return -1;
	}

	/**
	 * Creates a new Array by applying function `f` to all elements of `this`.
	 * The order of elements is preserved.
	 * If `f` is null, the result is unspecified.
	 * 
	 * @param \Closure $f
	 * 
	 * @return Array_hx
	 */
	public function map ($f) {
		#D:\haxe\haxe\std/php/_std/Array.hx:109: characters 3-35
		$result = [];
		#D:\haxe\haxe\std/php/_std/Array.hx:110: characters 15-18
		$data = $this->arr;
		$_g_current = 0;
		$_g_length = count($data);
		$_g_data = $data;
		#D:\haxe\haxe\std/php/_std/Array.hx:110: lines 110-112
		while ($_g_current < $_g_length) {
			$item = $_g_data[$_g_current++];
			#D:\haxe\haxe\std/php/_std/Array.hx:111: characters 4-24
			$result[] = $f($item);
		}

		#D:\haxe\haxe\std/php/_std/Array.hx:113: characters 3-22
		return Array_hx::wrap($result);
	}

	/**
	 * @param int $offset
	 * 
	 * @return bool
	 */
	public function offsetExists ($offset) {
		#D:\haxe\haxe\std/php/_std/Array.hx:199: characters 3-25
		return $offset < $this->length;
	}

	/**
	 * @param int $offset
	 * 
	 * @return mixed
	 */
	public function &offsetGet ($offset) {
		#D:\haxe\haxe\std/php/_std/Array.hx:204: lines 204-208
		try {
			#D:\haxe\haxe\std/php/_std/Array.hx:205: characters 4-22
			return $this->arr[$offset];
		} catch (\Throwable $__hx__caught_e) {
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#D:\haxe\haxe\std/php/_std/Array.hx:207: characters 4-15
			return null;
		}
	}

	/**
	 * @param int $offset
	 * @param mixed $value
	 * 
	 * @return void
	 */
	public function offsetSet ($offset, $value) {
		#D:\haxe\haxe\std/php/_std/Array.hx:213: lines 213-218
		if ($this->length <= $offset) {
			#D:\haxe\haxe\std/php/_std/Array.hx:214: lines 214-216
			$_g = $this->length;
			$_g1 = $offset + 1;
			while ($_g < $_g1) {
				$i = $_g++;
				#D:\haxe\haxe\std/php/_std/Array.hx:215: characters 5-18
				$this->arr[$i] = null;
			}

			#D:\haxe\haxe\std/php/_std/Array.hx:217: characters 4-23
			$this->length = $offset + 1;
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:219: characters 3-22
		$this->arr[$offset] = $value;
		#D:\haxe\haxe\std/php/_std/Array.hx:220: characters 3-35
		return $value;
	}

	/**
	 * @param int $offset
	 * 
	 * @return void
	 */
	public function offsetUnset ($offset) {
		#D:\haxe\haxe\std/php/_std/Array.hx:225: lines 225-228
		if (($offset >= 0) && ($offset < $this->length)) {
			#D:\haxe\haxe\std/php/_std/Array.hx:226: characters 4-39
			array_splice($this->arr, $offset, 1);
			#D:\haxe\haxe\std/php/_std/Array.hx:227: characters 4-12
			--$this->length;
		}
	}

	/**
	 * Removes the last element of `this` Array and returns it.
	 * This operation modifies `this` Array in place.
	 * If `this` has at least one element, `this.length` will decrease by 1.
	 * If `this` is the empty Array `[]`, null is returned and the length
	 * remains 0.
	 * 
	 * @return mixed
	 */
	public function pop () {
		#D:\haxe\haxe\std/php/_std/Array.hx:117: lines 117-118
		if ($this->length > 0) {
			#D:\haxe\haxe\std/php/_std/Array.hx:118: characters 4-12
			$this->length--;
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:119: characters 3-31
		return array_pop($this->arr);
	}

	/**
	 * Adds the element `x` at the end of `this` Array and returns the new
	 * length of `this` Array.
	 * This operation modifies `this` Array in place.
	 * `this.length` increases by 1.
	 * 
	 * @param mixed $x
	 * 
	 * @return int
	 */
	public function push ($x) {
		#D:\haxe\haxe\std/php/_std/Array.hx:123: characters 3-18
		$this->arr[$this->length] = $x;
		#D:\haxe\haxe\std/php/_std/Array.hx:124: characters 3-18
		return ++$this->length;
	}

	/**
	 * Removes the first occurrence of `x` in `this` Array.
	 * This operation modifies `this` Array in place.
	 * If `x` is found by checking standard equality, it is removed from `this`
	 * Array and all following elements are reindexed accordingly. The function
	 * then returns true.
	 * If `x` is not found, `this` Array is not changed and the function
	 * returns false.
	 * 
	 * @param mixed $x
	 * 
	 * @return bool
	 */
	public function remove ($x) {
		#D:\haxe\haxe\std/php/_std/Array.hx:127: lines 127-138
		$_gthis = $this;
		#D:\haxe\haxe\std/php/_std/Array.hx:128: characters 3-22
		$result = false;
		#D:\haxe\haxe\std/php/_std/Array.hx:129: lines 129-136
		$collection = $this->arr;
		foreach ($collection as $key => $value) {
			#D:\haxe\haxe\std/php/_std/Array.hx:130: lines 130-135
			if (Boot::equal($value, $x)) {
				#D:\haxe\haxe\std/php/_std/Array.hx:131: characters 5-39
				array_splice($_gthis->arr, $key, 1);
				#D:\haxe\haxe\std/php/_std/Array.hx:132: characters 5-13
				$_gthis->length--;
				#D:\haxe\haxe\std/php/_std/Array.hx:133: characters 5-18
				$result = true;
				#D:\haxe\haxe\std/php/_std/Array.hx:134: characters 5-25
				break;
			}
		}

		#D:\haxe\haxe\std/php/_std/Array.hx:137: characters 3-16
		return $result;
	}

	/**
	 * Set the length of the Array.
	 * If `len` is shorter than the array's current size, the last
	 * `length - len` elements will be removed. If `len` is longer, the Array
	 * will be extended, with new elements set to a target-specific default
	 * value:
	 * - always null on dynamic targets
	 * - 0, 0.0 or false for Int, Float and Bool respectively on static targets
	 * - null for other types on static targets
	 * 
	 * @param int $len
	 * 
	 * @return void
	 */
	public function resize ($len) {
		#D:\haxe\haxe\std/php/_std/Array.hx:189: lines 189-193
		if ($this->length < $len) {
			#D:\haxe\haxe\std/php/_std/Array.hx:190: characters 4-42
			$this->arr = array_pad($this->arr, $len, null);
		} else if ($this->length > $len) {
			#D:\haxe\haxe\std/php/_std/Array.hx:192: characters 4-47
			array_splice($this->arr, $len, $this->length - $len);
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:194: characters 3-15
		$this->length = $len;
	}

	/**
	 * Reverse the order of elements of `this` Array.
	 * This operation modifies `this` Array in place.
	 * If `this.length < 2`, `this` remains unchanged.
	 * 
	 * @return void
	 */
	public function reverse () {
		#D:\haxe\haxe\std/php/_std/Array.hx:141: characters 3-34
		$this->arr = array_reverse($this->arr);
	}

	/**
	 * Removes the first element of `this` Array and returns it.
	 * This operation modifies `this` Array in place.
	 * If `this` has at least one element, `this`.length and the index of each
	 * remaining element is decreased by 1.
	 * If `this` is the empty Array `[]`, `null` is returned and the length
	 * remains 0.
	 * 
	 * @return mixed
	 */
	public function shift () {
		#D:\haxe\haxe\std/php/_std/Array.hx:145: lines 145-146
		if ($this->length > 0) {
			#D:\haxe\haxe\std/php/_std/Array.hx:146: characters 4-12
			$this->length--;
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:147: characters 3-33
		return array_shift($this->arr);
	}

	/**
	 * Creates a shallow copy of the range of `this` Array, starting at and
	 * including `pos`, up to but not including `end`.
	 * This operation does not modify `this` Array.
	 * The elements are not copied and retain their identity.
	 * If `end` is omitted or exceeds `this.length`, it defaults to the end of
	 * `this` Array.
	 * If `pos` or `end` are negative, their offsets are calculated from the
	 * end of `this` Array by `this.length + pos` and `this.length + end`
	 * respectively. If this yields a negative value, 0 is used instead.
	 * If `pos` exceeds `this.length` or if `end` is less than or equals
	 * `pos`, the result is `[]`.
	 * 
	 * @param int $pos
	 * @param int $end
	 * 
	 * @return Array_hx
	 */
	public function slice ($pos, $end = null) {
		#D:\haxe\haxe\std/php/_std/Array.hx:151: lines 151-152
		if ($pos < 0) {
			#D:\haxe\haxe\std/php/_std/Array.hx:152: characters 4-17
			$pos += $this->length;
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:153: lines 153-154
		if ($pos < 0) {
			#D:\haxe\haxe\std/php/_std/Array.hx:154: characters 4-11
			$pos = 0;
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:155: lines 155-165
		if ($end === null) {
			#D:\haxe\haxe\std/php/_std/Array.hx:156: characters 4-45
			return Array_hx::wrap(array_slice($this->arr, $pos));
		} else {
			#D:\haxe\haxe\std/php/_std/Array.hx:158: lines 158-159
			if ($end < 0) {
				#D:\haxe\haxe\std/php/_std/Array.hx:159: characters 5-18
				$end += $this->length;
			}
			#D:\haxe\haxe\std/php/_std/Array.hx:160: lines 160-164
			if ($end <= $pos) {
				#D:\haxe\haxe\std/php/_std/Array.hx:161: characters 5-14
				return new Array_hx();
			} else {
				#D:\haxe\haxe\std/php/_std/Array.hx:163: characters 5-57
				return Array_hx::wrap(array_slice($this->arr, $pos, $end - $pos));
			}
		}
	}

	/**
	 * Sorts `this` Array according to the comparison function `f`, where
	 * `f(x,y)` returns 0 if x == y, a positive Int if x > y and a
	 * negative Int if x < y.
	 * This operation modifies `this` Array in place.
	 * The sort operation is not guaranteed to be stable, which means that the
	 * order of equal elements may not be retained. For a stable Array sorting
	 * algorithm, `haxe.ds.ArraySort.sort()` can be used instead.
	 * If `f` is null, the result is unspecified.
	 * 
	 * @param \Closure $f
	 * 
	 * @return void
	 */
	public function sort ($f) {
		#D:\haxe\haxe\std/php/_std/Array.hx:169: characters 3-15
		usort($this->arr, $f);
	}

	/**
	 * Removes `len` elements from `this` Array, starting at and including
	 * `pos`, an returns them.
	 * This operation modifies `this` Array in place.
	 * If `len` is < 0 or `pos` exceeds `this`.length, an empty Array [] is
	 * returned and `this` Array is unchanged.
	 * If `pos` is negative, its value is calculated from the end	of `this`
	 * Array by `this.length + pos`. If this yields a negative value, 0 is
	 * used instead.
	 * If the sum of the resulting values for `len` and `pos` exceed
	 * `this.length`, this operation will affect the elements from `pos` to the
	 * end of `this` Array.
	 * The length of the returned Array is equal to the new length of `this`
	 * Array subtracted from the original length of `this` Array. In other
	 * words, each element of the original `this` Array either remains in
	 * `this` Array or becomes an element of the returned Array.
	 * 
	 * @param int $pos
	 * @param int $len
	 * 
	 * @return Array_hx
	 */
	public function splice ($pos, $len) {
		#D:\haxe\haxe\std/php/_std/Array.hx:173: lines 173-174
		if ($len < 0) {
			#D:\haxe\haxe\std/php/_std/Array.hx:174: characters 4-13
			return new Array_hx();
		}
		#D:\haxe\haxe\std/php/_std/Array.hx:175: characters 3-57
		$result = Array_hx::wrap(array_splice($this->arr, $pos, $len));
		#D:\haxe\haxe\std/php/_std/Array.hx:176: characters 3-26
		$this->length -= $result->length;
		#D:\haxe\haxe\std/php/_std/Array.hx:177: characters 3-16
		return $result;
	}

	/**
	 * Returns a string representation of `this` Array.
	 * The result will include the individual elements' String representations
	 * separated by comma. The enclosing [ ] may be missing on some platforms,
	 * use `Std.string()` to get a String representation that is consistent
	 * across platforms.
	 * 
	 * @return string
	 */
	public function toString () {
		#D:\haxe\haxe\std/php/_std/Array.hx:185: characters 10-54
		$arr = $this->arr;
		$strings = [];
		foreach ($arr as $key => $value) {
			$strings[$key] = Boot::stringify($value, 9);
		}
		return "[" . (implode(",", $strings)??'null') . "]";
	}

	/**
	 * Adds the element `x` at the start of `this` Array.
	 * This operation modifies `this` Array in place.
	 * `this.length` and the index of each Array element increases by 1.
	 * 
	 * @param mixed $x
	 * 
	 * @return void
	 */
	public function unshift ($x) {
		#D:\haxe\haxe\std/php/_std/Array.hx:181: characters 3-40
		$this->length = array_unshift($this->arr, $x);
	}

	public function __toString() {
		return $this->toString();
	}
}

Boot::registerClass(Array_hx::class, 'Array');
