<?php
/**
 * Generated by Haxe 4.0.5
 */

namespace php\_Boot;

use \php\Boot;

/**
 * Closures implementation
 */
class HxClosure {
	/**
	 * @var mixed
	 * A callable value, which can be invoked by PHP
	 */
	public $callable;
	/**
	 * @var string
	 * Method name for methods
	 */
	public $func;
	/**
	 * @var mixed
	 * `this` for instance methods; php class name for static methods
	 */
	public $target;

	/**
	 * @param mixed $target
	 * @param string $func
	 * 
	 * @return void
	 */
	public function __construct ($target, $func) {
		#D:\haxe\haxe\std/php/Boot.hx:969: characters 3-23
		$this->target = $target;
		#D:\haxe\haxe\std/php/Boot.hx:970: characters 3-19
		$this->func = $func;
		#D:\haxe\haxe\std/php/Boot.hx:972: lines 972-974
		if (is_null($target)) {
			#D:\haxe\haxe\std/php/Boot.hx:973: characters 4-9
			throw new HxException("Unable to create closure on `null`");
		}
		#D:\haxe\haxe\std/php/Boot.hx:975: characters 14-98
		$tmp = null;
		if (($target instanceof HxAnon)) {
			#D:\haxe\haxe\std/php/Boot.hx:975: characters 52-58
			$tmp1 = $target;
			#D:\haxe\haxe\std/php/Boot.hx:975: characters 14-98
			$tmp = $tmp1->{$func};
		} else {
			$tmp = [$target, $func];
		}
		#D:\haxe\haxe\std/php/Boot.hx:975: characters 3-98
		$this->callable = $tmp;
	}

	/**
	 * @see http://php.net/manual/en/language.oop5.magic.php#object.invoke
	 * 
	 * @return mixed
	 */
	public function __invoke () {
		#D:\haxe\haxe\std/php/Boot.hx:983: characters 3-71
		return call_user_func_array($this->callable, func_get_args());
	}

	/**
	 * Invoke this closure with `newThis` instead of `this`
	 * 
	 * @param mixed $newThis
	 * @param mixed $args
	 * 
	 * @return mixed
	 */
	public function callWith ($newThis, $args) {
		#D:\haxe\haxe\std/php/Boot.hx:1010: characters 3-65
		return call_user_func_array($this->getCallback($newThis), $args);
	}

	/**
	 * Check if this is the same closure
	 * 
	 * @param HxClosure $closure
	 * 
	 * @return bool
	 */
	public function equals ($closure) {
		#D:\haxe\haxe\std/php/Boot.hx:1003: characters 10-60
		if (Boot::equal($this->target, $closure->target)) {
			#D:\haxe\haxe\std/php/Boot.hx:1003: characters 39-59
			return $this->func === $closure->func;
		} else {
			#D:\haxe\haxe\std/php/Boot.hx:1003: characters 10-60
			return false;
		}
	}

	/**
	 * Generates callable value for PHP
	 * 
	 * @param mixed $eThis
	 * 
	 * @return mixed
	 */
	public function getCallback ($eThis = null) {
		#D:\haxe\haxe\std/php/Boot.hx:990: lines 990-992
		if ($eThis === null) {
			#D:\haxe\haxe\std/php/Boot.hx:991: characters 4-18
			$eThis = $this->target;
		}
		#D:\haxe\haxe\std/php/Boot.hx:993: lines 993-995
		if (($eThis instanceof HxAnon)) {
			#D:\haxe\haxe\std/php/Boot.hx:994: characters 24-29
			$tmp = $eThis;
			#D:\haxe\haxe\std/php/Boot.hx:994: characters 4-36
			return $tmp->{$this->func};
		}
		#D:\haxe\haxe\std/php/Boot.hx:996: characters 3-39
		return [$eThis, $this->func];
	}
}

Boot::registerClass(HxClosure::class, 'php._Boot.HxClosure');
